### ISSUE TITLE
Support Abilities bug? (Bravely Second)

### ISSUE THREAD

**Issue by AugmentedAntics** [MarvinXLII/BravelyRandomize#1]
Either I'm missing something, or this appears to be a bug: for some reason, Support Abilities will not stay equipped. Viewing the equipment screen or exiting a battle just unequips them. All possible options for randomization are enabled except Mastered Jobs.

**Comment by MarvinXLII** [comment]
Not so much a bug, rather an oversight on my part. The majority of my testing was on BD and I guess I didn't notice the issue on BS. Thanks for bringing to my attention!

I have no clue how to fix it at the moment. To continue your playthrough, I'd recommend generating a new patch with all the same settings and seeds EXCEPT for shuffling support abilities. Everything else will be shuffled the same way, and the vanilla support abilities will not be removed during battle.

**Comment by MarvinXLII** [comment]
In short, BS required an extra column of data to be updated than BD for support skills to work properly.  I'll explore this more in BD to see if there are any other side effects, but so far I see no issues with it.

This issue is now fixed and released in version 0.2.2. Thank for finding and reporting the issue!
