### ISSUE TITLE
One support ability missing [Bravely Default]

### ISSUE THREAD

**Issue by Color-Printer** [MarvinXLII/BravelyRandomize#2]
Late Bloomer is shuffled along with the other support abilities, but it's not an ability Freelancer learns as a equippable support. It's the only specialty that the respective job doesn't learn through leveling up. This means there's an extra support ability in the pool, so one support ability will always be left out (unless random job specialties are turned on and it happens to get picked for one of them). This isn't too bad if it's a random stat up or element immunity, but it's kind of a downer if it's something like Dual Wield. Or even worse, Genome Drain.

(Not sure if anything like this happens with Bravely Second)

**Comment by MarvinXLII** [comment]
Thanks for the feedback. I intentionally designed it like that because, at least to me, it keeps things interesting. This sort of thing shouldn't happen in Bravely Second, but if I remember correctly, that game does include unused support abilities like 10% and 30% stat boosts. Including those in the randomizer, which I've considered adding at some point, would lead some support abilities being omitted.

I'll keep this issue open for the time being to encourage others to voice their opinions.

**Comment by Color-Printer** [comment]
Considering it's kind of unlikely you'd see all possible job unlocks without looking at the spoiler file anyway (unless you decide to play a seed out completely 100%, I guess) I'm actually willing to say that's fine now that I think about it. I'm at least glad to see it's an intentional choice and not a mistake.
